// Auto-generated by scripts/upload-assets-to-cloudinary.cjs on 2026-07-28T16:46:43.662Z
export const media = {
  logoHome: "https://res.cloudinary.com/dubm71ocj/image/upload/v1785257188/techxpert-static/logoHome.png",
  logoNav: "https://res.cloudinary.com/dubm71ocj/image/upload/v1785257189/techxpert-static/logoNav.png",
  logoClass: "https://res.cloudinary.com/dubm71ocj/image/upload/v1785257191/techxpert-static/logoclass.png",
  logoFoot: "https://res.cloudinary.com/dubm71ocj/image/upload/v1785257192/techxpert-static/logofoot.png",
  back1: "https://res.cloudinary.com/dubm71ocj/image/upload/v1785257194/techxpert-static/back1.png",
  back2: "https://res.cloudinary.com/dubm71ocj/image/upload/v1785257195/techxpert-static/back2.png",
  back3: "https://res.cloudinary.com/dubm71ocj/image/upload/v1785257196/techxpert-static/back3.png",
  certificateTemplate: "https://res.cloudinary.com/dubm71ocj/image/upload/v1785257198/techxpert-static/certificate.jpg",
  video1: "https://res.cloudinary.com/dubm71ocj/video/upload/v1785257200/techxpert-static/video1.mp4",
};
